### ISSUE TITLE
core: Plugin configuration

### ISSUE THREAD

**Issue by VoyTechnology** [VoyTechnology/cheapskate#13]
Right now none of the plugins require configuration, but it will change soon, as things such as Facebook or Github would definitely need API keys to work.

I guess the easiest way to configure it would be to have `plugins.config.<name>.*`, where `<name>` is the name of the plugin. This way on plugin creation we can call `Configure(config map[string]interface{})` where the the passed in data would correspond to `*`.

eg.

cheapskate.toml

```yaml
plugins:
  config:
    facebook:
      email: _________@______
      password: ____________
```

and Config passed into the plugin would only have the fields`email` and `password` available.

This is a meh security measure, as all plugins still have access to `settings` package which contains all the values.
